# Generated by Django 3.2.6 on 2021-09-28 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0001_initial'),
        ('Players', '0002_auto_20210928_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerData',
            fields=[
                ('PlayerId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Players.user')),
                ('PlayerCellNumber', models.CharField(max_length=15)),
                ('PlayerDob', models.DateField()),
                ('Rank', models.IntegerField()),
                ('PlayerProgress', models.IntegerField()),
                ('CoachName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.coachdata')),
            ],
        ),
        migrations.CreateModel(
            name='ParentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentDetails', models.CharField(max_length=200)),
                ('CoachName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Coach.coachdata')),
                ('ParentId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('PlayerName', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Players.playerdata')),
            ],
        ),
    ]
