# Generated by Django 3.2.6 on 2021-09-29 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0004_alter_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerdata',
            name='PlayerDob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='PlayerProgress',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='playerdata',
            name='Rank',
            field=models.IntegerField(default=0),
        ),
    ]
