# Generated by Django 3.2.6 on 2021-09-29 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0006_alter_playerdata_coachname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentdata',
            name='CoachName',
        ),
    ]
