# Generated by Django 3.2.6 on 2021-09-29 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0007_remove_parentdata_coachname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentdata',
            name='PlayerName',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Players.playerdata'),
        ),
    ]
