# Generated by Django 3.2.6 on 2021-10-05 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0009_alter_playerdata_playercellnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playerdata',
            old_name='PlayerProgress',
            new_name='score',
        ),
        migrations.RemoveField(
            model_name='playerdata',
            name='Rank',
        ),
    ]
