# Generated by Django 3.2.6 on 2021-10-06 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0010_auto_20211005_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentdata',
            name='ParentDetails',
        ),
        migrations.RemoveField(
            model_name='parentdata',
            name='PlayerName',
        ),
    ]
