# Generated by Django 3.2.6 on 2021-09-28 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Players', '0002_auto_20210928_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoachData',
            fields=[
                ('CoachId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Players.user')),
                ('CoachDetails', models.CharField(max_length=200)),
            ],
        ),
    ]
