# Generated by Django 3.2.6 on 2021-09-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CatName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VedioContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VedioTitle', models.CharField(max_length=200)),
                ('Desc', models.TextField()),
                ('vedio', models.FileField(upload_to='vedios/<django.db.models.fields.related.ForeignKey>')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.category')),
            ],
        ),
    ]
