# Generated by Django 3.2.6 on 2021-09-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0002_category_vediocontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdata',
            name='CoachNumber',
            field=models.CharField(default=123, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
