# Generated by Django 3.2.6 on 2021-10-01 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0003_coachdata_coachnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachdata',
            name='vedios',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coach.vediocontent'),
        ),
    ]
