# Generated by Django 3.2.6 on 2021-10-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0004_coachdata_vedios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coachdata',
            name='vedios',
        ),
        migrations.AddField(
            model_name='vediocontent',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coach.coachdata'),
        ),
    ]
