# Generated by Django 3.2.6 on 2021-10-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0006_alter_vediocontent_vedio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vediocontent',
            name='vedio',
            field=models.FileField(upload_to='vedio/%y'),
        ),
    ]
