# Generated by Django 3.2.6 on 2021-10-03 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Players', '0009_alter_playerdata_playercellnumber'),
        ('Coach', '0008_vediocontent_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='VedioSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('UploadedVedio', models.FileField(upload_to='upload/%y')),
                ('marks', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Players.playerdata')),
                ('vedio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Coach.vediocontent')),
            ],
        ),
    ]
