# Generated by Django 3.2.6 on 2021-10-04 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0009_vediosubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='vediosubmission',
            name='submit',
            field=models.BooleanField(default=False),
        ),
    ]
