# Generated by Django 3.2.6 on 2021-10-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Coach', '0010_vediosubmission_submit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vediosubmission',
            name='marks',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
